### ISSUE TITLE
Vehicle Quick Select styling not enabled even with option

### ISSUE THREAD

**Issue by shawnlehner** [Burkson/ridestyler.customer.widgets#8]
It appears there is something which causes the styling to not be displayed, even if the option is enabled via the editor. We should make sure that if the styles are enabled, the result is a nice looking implementation of the widget. They can use this as a base and override it themselves, or disable them to come up with their own styling.

![image](https://user-images.githubusercontent.com/5307103/72572709-44d0ff80-3878-11ea-923d-ecc5d502b266.png)

**Comment by bbless97** [comment]
Updated QuickSelect styling to this when enabled:
![image](https://user-images.githubusercontent.com/47756879/72638655-bbbdd500-3918-11ea-9974-5632341e09b3.png)

**Comment by shawnlehner** [comment]
Can we go with more of this style for the basic styling? I think the more traditional combo box style and such will fit better by default with most websites.

![image](https://user-images.githubusercontent.com/5307103/72754040-9250b380-3b7b-11ea-912f-8af463020517.png)

**Comment by bbless97** [comment]
Updated default styling: 
![image](https://user-images.githubusercontent.com/47756879/73208375-33e78000-40fb-11ea-8cba-70de5f37cf25.png)
